name: dynamic_app_theme
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^3.0.0
  #shared_preferences: ^0.5.6+3
  flare_flutter: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/day_night.flr
    - assets/animation.flr
    - assets/anim_with_pager.flr
    - assets/swipeleft.flr

    - assets/indicator.flr




